apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-pod
spec:
  replicas: 1
  strategy:
    type: Recreate
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service
spec:
  type: LoadBalancer
